---
# tasks file for system_upgrade
- name: Update package cache
  become: true
  ansible.builtin.package:
    update_cache: true
    cache_valid_time: "{{ system_upgrade_cache_valid_time }}"

- name: Install critical packages
  become: true
  ansible.builtin.package:
    name: "{{ system_upgrade_critical_packages }}"
    state: latest
  when: system_upgrade_critical_packages | length > 0

- name: Upgrade all system packages
  become: true
  ansible.builtin.package:
    upgrade: true

- name: Check if reboot is required
  ansible.builtin.stat:
    path: "{{ system_upgrade_reboot_required_file_path }}"
