---
# tasks file for vim
- name: Install Vim and related packages
  become: true
  ansible.builtin.package:
    name: "{{ vim_packages }}"
    state: present
    update_cache: true

- name: Configure Vim system-wide
  become: true
  ansible.builtin.template:
    src: vimrc.j2
    dest: /etc/vim/vimrc.local
    owner: root
    group: root
    mode: "0644"
