---
# tasks file for ssh
- name: Install SSH packages
  become: true
  ansible.builtin.apt:
    name: "{{ ssh_packages }}"
    state: present
    update_cache: true

- name: Start and enable SSH service
  become: true
  ansible.builtin.systemd:
    name: "ssh"
    state: started
    enabled: true

- name: Create /etc/skel/.ssh directory
  become: true
  ansible.builtin.file:
    path: /etc/skel/.ssh
    state: directory
    mode: '0700'
    owner: root
    group: root

- name: Install SSH client configuration in skel
  become: true
  ansible.builtin.template:
    src: skel_ssh_config.j2
    dest: /etc/skel/.ssh/config
    mode: '0600'
    owner: root
    group: root
