---
# main tasks file for admin role

- name: Create Group wheel
  become: true
  ansible.builtin.group:
    name: wheel
    gid: 500
    state: present

- name: Create Group wheel_no_pswd
  become: true
  ansible.builtin.group:
    name: wheel_no_pswd
    gid: 501
    state: present

- name: Set sudo for wheel
  become: true
  ansible.builtin.copy:
    content: "%wheel ALL=(ALL:ALL) ALL"
    dest: /etc/sudoers.d/wheel
    mode: "0440"
    validate: "/usr/sbin/visudo -cf %s"

- name: Set sudo without password for wheel_no_pswd
  become: true
  ansible.builtin.copy:
    content: "%wheel_no_pswd ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/wheel_no_pswd
    mode: "0440"
    validate: "/usr/sbin/visudo -cf %s"

- name: Disable sudo admin success message
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/sudoers"
    line: "Defaults !tty_tickets"
    validate: 'visudo -cf %s'
