---
# tasks file for create_user

- name: Create user
  become: true
  ansible.builtin.user:
    name: "{{ user_data.name }}"
    comment: "{{ user_data.comment }}"
    groups: "{{ user_data.groups }}"
    password: "{{ user_data.password | password_hash('sha512') }}"
    state: "{{ user_data.state }}"
    shell: "{{ user_data.shell }}"
    update_password: always

- name: Copy skel content for existing users
  become: true
  ansible.builtin.copy:
    src: /etc/skel/
    dest: "/home/{{ user_data.name }}/"
    owner: "{{ user_data.name }}"
    group: "{{ user_data.name }}"
    mode: preserve
    backup: true
    remote_src: true
  when:
    - user_data.state == "present"
