---
# tasks file for zsh
- name: Install ZSH and related packages
  become: true
  ansible.builtin.package:
    name: "{{ zsh_packages }}"
    state: present
    update_cache: true

- name: Copy ZSH configuration files
  become: true
  ansible.builtin.copy:
    src: etc/
    dest: /etc/zsh
    mode: "0644"
    owner: root
    group: root

- name: Copy ZSH configuration to skel
  ansible.builtin.copy:
    src: files/home/
    dest: "/etc/skel/"
    owner: root
    group: root
    mode: '0644'
    directory_mode: '0755'

- name: Copy ZSH configuration to root home
  become: true
  ansible.builtin.copy:
    src: files/home/
    dest: "/root/"
    owner: root
    group: root
    mode: '0644'
    directory_mode: '0755'

- name: Set root shell to zsh
  become: true
  ansible.builtin.user:
    name: root
    shell: /bin/zsh
